### ISSUE TITLE
Edição de canções 1-20, coleção Pixinguinha

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#1]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [guia de realização de tarefas da pesquisa](http://genosmus.com/pesquisa/contornos/choro/guia/)
- A [página da pesquisa](http://genosmus.com/pesquisa/contornos/choro/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. NÃO USAR EMAIL. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.

**Comment by msampaio** [comment]
Neste primeiro commit, colocar os arquivos .mus e .xml dentro do diretório do Dropbox, organizado em choros-corpus/Pixinguinha. Deixar a inserção dos xml no repositório para os demais commit.

**Comment by EduardoNunes** [comment]
Aqui contem erros nas edições. Tanto erros sobre coisas que eu ainda preciso pesquisar no finale, quanto erros de escrita do próprio livro de choros.

Música 03 - Tem um defeito na repetição que ainda tenho que pesquisar como consertar, e um defeito no Fine.
Música 04 - Está tudo OK, porém tem uma segunda voz que me parece fazer parte da melodia, mas não escrevi.
Música 08 - Acredito que as repetições escritas no livro estejam erradas e que o copista esqueceu de colocar o 'FIM' da música.
Música 09 - Tem um pequeno defeito no último compasso.
Música 11 - Tem um defeito na repetição do ritornello que eu vou pesquisar pra saber como consertar.
Música 12 - Defeito no ritornello e no fine.
Música 13 - Não tem indicação de 'FIM' na partitura.
Música 15 - Compassos de pausa e símbolos de bateria.
Música 19 - Não colocaram o sinal de segno.

**Comment by msampaio** [comment]
Coloque os arquivos .mus e .xml do que você já fez na pasta Drobpox. Veja instruções no [guia](http://genosmus.com/pesquisa/contornos/choro/guia/). Faça as edições direto no Dropbox, como sempre fizemos na disciplina de Composição.
Além disso vamos criar um arquivo para documentar todos os problemas que você falou aqui.

**Comment by msampaio** [comment]
Na música "Ainda me recordo" escrever a duas vozes para usarmos como experimento para análise de contornos polifônicos.
