### ISSUE TITLE
Programar função para fazer comparações entre o compositor e uma coleção de dados

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#100]
Esta função poderá retornar um vetor com os dados de uma coleção dada, e de um compositor dado. O objetivo é comparar do tipo "âmbitos de Pixinguinha x Waldir Azevedo", ou "intervalos de compositores de sopro e todos os compositores exceto Pixinguinha".
Esta função poderá ter recursos adicionais para gerar gráfico comparativo e uma planilha.

**Comment by msampaio** [comment]
A função de gerar vetores está pronta. Já existia função para isso no módulo `matrix`. Para criar uma função para gerar gráficos é preciso refatorar toda a geração de matriz, gráfico e página web de resultados.
O ideal é criar funções independentes do módulo `webpage`, para gerar os dados numéricos, para gerar os gráficos e para gerar a página de resultados.

**Comment by msampaio** [comment]
Ótimo, @SaraFadigas. Por favor informe aqui como você está fazendo para verificar essas técnicas. Precisamos avançar neste estudo estatístico.
No processo de refatoração eu criei uma função (commit 5466cd9) para cruzar dados de todos os parâmetros musicais, como âmbito, contorno, duração, com todas as informações musicológicas, como ano de nascimento, instrumento principal, etc. Com isso poderemos ir além do estudo baseado apenas no nome do compositor.

**Comment by SaraFadigas** [comment]
Transpus a tabela para melhor visualizar os dados. Em seguida somei todas as ocorrências de intervalos de cada compositor, e então calculei a porcentagem de ocorrência de cada tipo de intervalo. com esses dados eu posso ter uma idéia geral do uso dos intervalos por compositor. A partir daí pensei em fazer uma média aritmética das menores porcentagens de ocorrências de intervalos pra estabelecer um ponto de corte. Vou colocar o arquivo no dropbox com essas novas tabelas assim que terminar essa média.

**Comment by msampaio** [comment]
Ótimo, @SaraFadigas. Siga em frente e me atualize.
