### ISSUE TITLE
Revisar choros com problemas

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#104]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [guia de realização de tarefas da pesquisa](http://genosmus.com/pesquisa/contornos/choro/guia/). Há uma seção específica sobre o formato do arquivo de segmentação.
- A [página da pesquisa](http://genosmus.com/pesquisa/contornos/choro/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. NÃO USAR EMAIL. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

A tarefa consiste em verificar os choros listados no arquivo `Todas as dúvidas.txt` e resolver os seus problemas.
É necessário terminar a tarefa o quanto antes para poder resolver todos os problemas até o dia 30/07/2013.

**Comment by AlissonGSilva** [comment]
Revisei todos os listados, inclusive abri os arquivos .form.
O único problema que persiste são alguns choros que tem uma forma confusa, criando insegurança quanto a segmentação. A maioria dos choros tem problemas nas partituras originais.

**Comment by ZeRodriguez** [comment]
@AlissonGSilva, preciso de sua ajuda. No arquivo `Todas as dúvidas.txt`, revisado por você nessa tarefa, ao lado das anotações há um `(OK)`. Você que colocou esse `(OK)`? Significa que as dúvidas foram sanadas?
Obrigado.

**Comment by AlissonGSilva** [comment]
É isso mesmo.Significa que as dúvidas foram sanadas.
Pus o (OK) pra eu saber quais já tinha verificado e resolvido.

**Comment by ZeRodriguez** [comment]
Como eu imaginava. Obrigado @AlissonGSilva.
