### ISSUE TITLE
Revisar segmentações da coleção O Melhor do choro vol 1

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#105]
Verificar se as segmentações da coleção estão corretas. Registrar aqui todos os casos em que precisar alterar as segmentações.

**Comment by ZeRodriguez** [comment]
@SimeiFerreira, preciso de sua ajuda para terminar minha tarefa #108 . Como não há comentários nessa tarefa, não sei se ela foi concluída. As revisões foram feitas?
Obrigado!

**Comment by SimeiFerreira** [comment]
Ainda não @ZeRodriguez, tirei o dia hoje para concluir as pendências das últimas tarefas.

**Comment by ZeRodriguez** [comment]
Certo @SimeiFerreira. Eu acabei revisando algumas. Eu abri os arquivos `.form` e revisei apenas os que haviam algumas peculiaridades, como períodos com 3 frases. Corrigi algumas coisas. O que foi corrigido por mim, pode ser visto no meu comentário na tarefa #108 . Lá há uma bula do que eu fiz, e há referência à essa tarefa.

**Comment by SimeiFerreira** [comment]
Tranquilo @ZeRodriguez, vou revisar os que você não revisou.

**Comment by SimeiFerreira** [comment]
@msampaio, preciso que você gere um novo numbered xml para o choro 1 "A bicada do tico tico" da coleção "O melhor do choro vol. 1", um compasso fora "engolido" durante a expansão do mesmo e por isso não pude corrigir a segmentação do mesmo. Já inclui o referido compasso no arquivo .mus expandido.

**Comment by msampaio** [comment]
@SimeiFerreira, estou com um problema com a segmentação da música 7 dessa coleção. Não consigo identificar o lugar exato do problema. Você pode ver se há algo errado?

**Comment by msampaio** [comment]
@SimeiFerreira, já gerei o arquivo enumerado.

**Comment by msampaio** [comment]
@SimeiFerreira, tem algum problema com as segmentações dos choros 7, 14, e 43. Por favor corrija-os.

**Comment by ZeRodriguez** [comment]
@msampaio, você pode dá uma olhada num comentário que acabei de fazer na tarefa #102 ? Fiz um questionamento à Simei. Se eu estiver certo, esse foi o erro do choro número 14. Estou com ele em aberto esperando uma resposta para corrigi-lo.

**Comment by SimeiFerreira** [comment]
@ZeRodriguez, você revisou algum choro além dos marcados na tarefa #108?

**Comment by ZeRodriguez** [comment]
@SimeiFerreira, só os listados na letra (F). Como comentei antes, nessa mesma tarefa, eu abri todos os arquivos `.form`, mas só corrigi os que tinham coisas incomuns, como períodos com 3 frases. Então, os que não estão listados lá não foram corrigidos.

**Comment by SimeiFerreira** [comment]
Certo, vou fazer uma revisão da sua revisão então hahaha.

**Comment by ZeRodriguez** [comment]
Fique a vontade... Hahaha

**Comment by msampaio** [comment]
@ZeRodriguez, o único problema agora é com o choro 7. Falta apenas essa música para concluirmos as segmentações :-)

**Comment by ZeRodriguez** [comment]
@msampaio, a respeito do choro número 7, "BH", estava dando uma olhada nele ontem com @AlissonGSilva. Vimos, revimos, chegamos até a abrir o arquivo `numbered` e ainda assim não conseguimos identificar erro algum.

**Comment by msampaio** [comment]
@ZeRodriguez, @SimeiFerreira e @AlissonGSilva, encontrei o problema no choro 7. Há um segmento de dois eventos (vide figura) `l 690 691`. O programa está quebrando exatamente neste segmento. Como não se trata de uma frase, eu vou remover esse segmento da análise.

![screen shot 2013-08-03 at 15 47 11](https://f.cloud.github.com/assets/1006488/906098/731e1286-fc6d-11e2-8ace-81789f3d2bba.png)

**Comment by AlissonGSilva** [comment]
Consertei isso, eu não exclui não, dei uma olhada e escrevi o evento 690 e 691 na frase seguinte.
Loucura minha esse link de 690 691.
