### ISSUE TITLE
Revisar segmentações da coleção O Melhor do choro vol 2

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#106]
Verificar se as segmentações da coleção estão corretas. Registrar aqui todos os casos em que precisar alterar as segmentações.

**Comment by ZeRodriguez** [comment]
@msampaio, a respeito dessa tarefa, é para revisar o livro inteiro, não é isso?

**Comment by msampaio** [comment]
Sim. Basta ouvir as musicas no arquivo enumerado junto com o arquivo form. Recomendo primeiro anotar o que vc terá que rever. Depois vc volta para corrigir.

**Comment by ZeRodriguez** [comment]
@msampaio, tranquilo fessô. Estou familiarizado com o  procedimento. As revisões têm sido bem tranquilas. Existem pequenos erros, mas têm sido bem recorrentes. Uma frase termina em 10 e a seguinte começa em 11. Quem segmentou, colocou que a frase termina em 11 e a seguinte também começando em 11. Fora isso, sem problemas.

**Comment by ZeRodriguez** [comment]
@msampaio, já fiz grande parte da revisão. Eu não sei quem a segmentou, mas eu penso diferente. Gostaria de tirar essa dúvida. Em muitos casos, depois que a frase se encerra, tem uma espécie de codeta. Geralmente um arpejo. Por exemplo, a frase encerra no Dó 3, e ele segue com um arpejo do acorde e termina no Dó 4. Eu considero essa "codeta" como um apequena extensão ainda fazendo parte da frase. A pessoa que segmentou, diversos momentos considerou essas pequenas partes como link. Nas revisões que fiz, "consertei" isso de acordo com o meu raciocínio. Queria saber se estou certo.

**Comment by msampaio** [comment]
@ZeRodriguez, registre aqui todas as músicas que você alterou.

**Comment by ZeRodriguez** [comment]
@msampaio, fui seguindo a ordem das músicas. Ontem fiz da número 1 até a número 25. Nem todas precisaram de mudanças. Mas como eu editei o arquivo .form direto do dropbox, eu não tenho como dizer quais músicas foram alteradas. Tem algum problema nisso?

**Comment by msampaio** [comment]
@ZeRodriguez, você tem como dizer quais músicas foram alteradas. Basta ir na página do Dropbox, clicar em events, escolher a pasta genos-choros e procurar as músicas que você alterou. Veja na imagem abaixo:

![screen shot 2013-07-25 at 07 37 06](https://f.cloud.github.com/assets/1006488/855063/7279fe3e-f516-11e2-8aa8-affaf3e38a54.png)

**Comment by ZeRodriguez** [comment]
@msampaio, tranquilo. Essas são as que eu editei:

1, 2, 3, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 23, 24, 25, 26, 27, 28

Até o momento só essas. Como falei antes, as primeiras tiveram problemas de erro de digitação dos números, as segmentações estavam similares. Quanto a minha segunda dúvida, em relação aos links, as músicas número 26 e 28 exemplificam bem, logo no início.

**Comment by msampaio** [comment]
@ZeRodriguez, apenas as músicas 4, 8, 18, 21, 22, 29 e 30 estavam corretas?

**Comment by ZeRodriguez** [comment]
@msampaio, isso mesmo. Mas como eu falei, a maioria não tinha erros na segmentação, e sim na escrita.
Exemplo, a frase A termina em 10 e a B começa em 11. Quem segmentou colocou a A terminando em 11 e a B começando em 11.

**Comment by ZeRodriguez** [comment]
@msampaio, estou continuando com as revisões. Dessa vez, fazendo relatório. Facilita bastante. A número 46, "Saxofone Por Que Choras" está sem o arquivo numerado. Assim, não dá para revisar.

**Comment by SimeiFerreira** [comment]
@ZeRodriguez, eu segmentei a coleção o melhor do choro 2. Nos choros que você citou, eu segmentei daquela forma porque achei que havia uma elisão entre as frases, mesmo sem haver um link entre as mesmas.

**Comment by msampaio** [comment]
@ZeRodriguez, coloquei o arquivo enumerado da música 46 na pasta do Dropbox.

**Comment by ZeRodriguez** [comment]
Tranquilo @msampaio e @SimeiFerreira.

**Comment by ZeRodriguez** [comment]
@msampaio,tarefa concluída.

**Comment by msampaio** [comment]
@ZeRodriguez, por favor corrija esses erros:

```
Error in file choros-corpus/O melhor do choro brasileiro vol 2/12 - choro n1.form
0:  # part
Error in file choros-corpus/O melhor do choro brasileiro vol 2/39 - pedacinho do céu.form
2: 3p 3 34
```

**Comment by ZeRodriguez** [comment]
Corrigido @msampaio.

**Comment by msampaio** [comment]
Bom trabalho, @ZeRodriguez. Fechando tarefa.
