### ISSUE TITLE
Revisar edição da música 11 - Carinhoso, da coleção O Melhor de Pixinguinha

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#107]
Entre os compassos 39 e 47 há uma modulação inexistente no original. Ver se há outros problemas do tipo. Corrigir os arquivos das pastas `expandidos` e `originais`.

**Comment by ZeRodriguez** [comment]
@msampaio, vi agora que mesmo na pasta das originais, a música foi transcrita com alguns equívocos. Ela terá que ser refeita desde o original para depois expandir. Depois de expandida, avisarei para que o senhor possa gerar o arquivo "numbered", para que possa ser feita a segmentação. Contudo, talvez essa tarefa não possa ser concluída para amanhã. Mas tentarei concluí-la.

**Comment by msampaio** [comment]
@ZeRodriguez, veja se tem como aproveitar o arquivo original. Não será difícil expandir com ele pronto.

**Comment by ZeRodriguez** [comment]
@msampaio, já fiz uma nova edição. Só falta expandir. Ainda não o fiz pois tenho dúvidas, visto que não havia feito nenhuma expansão. Já estou tirando minhas dúvidas e concluirei esta tarefa o quanto antes.

**Comment by ZeRodriguez** [comment]
@msampaio, expansão concluída. Estou a espera do arquivo `numbered`para revisar a segmentação.

**Comment by ZeRodriguez** [comment]
@msampaio, como a revisão da segmentação não é tópico desta tarefa, a classificarei como concluída no meu mapeamento da tarefa #108 .
