### ISSUE TITLE
Mapear o estado atual do cumprimento de tarefas

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#108]
Identificar aqui quais das tarefas em aberto já estão cumpridas. Esta tarefa implica em olhar na pasta Dropbox se os arquivos estão presentes ou não. Caso a tarefa esteja cumprida, lista-la aqui. Para listar a tarefa 100, por exemplo, basta indicar `#100` para ver aparecer #100.

**Comment by ZeRodriguez** [comment]
#85 - Problemas discutidos em reunião a respeito de etnomusicologia. Conclusão da tarefa suejeita a você.
#86 - Tarefa direcionada a você. Conclusão da tarefa suejeita a você.
#91 - Tarefa concluída.(A)
#92 - Tarefa concluída.
#93 - Não há como avaliar por completo a tarefa. Conclusão da tarefa suejeita a você.
#94 - Tarefa direcionada a você. Conclusão da tarefa suejeita a você. Tarefa relacionada à #93
#96 - Tarefa concluída.(B)
#97 - Tarefa concluída.(C)
#99 - Tarefa direcionada a você. Conclusão da tarefa suejeita a você.
#100 - Tarefa direcionada a você. Conclusão da tarefa suejeita a você.
#102 - Tarefa concluída.(D) (E)
#103 - Tarefa concluída.
#104 - Aguardando resposta de Alisson. Acredito que a tarefa tenha sido concuída.
#105 - Aguardando resposta de Simei. Acredito que a tarefa tenha sido concluída.(F)
#107 - Tarefa concluída. 

(A) - Correção de segmentação em número `03`.
(B) - Correção de formatação da segmentação em número `27`. 
      Correção da nomencltura do arquivo em número `29`.
(C) - Tarefa consiste na expansão dos choros `60-72` do livro "O Melhor de Pixinguinha." 
      Livro contém apenas `71` músicas.
(D) - Correção de segmentação em números `33`, `35`, `38` e `41`.
(E) - Tarefa não havia sido concluída. Choros números `42`, `43`, `44`e `45`foram segmentados por mim.
(F) - Correção de segmentação em número `05`e segmentação e nomenclatura em número `07`.
      Correção de segmentação em números `12`, `14`, `16`e `21`.
      Correção de formatação em número `24`.
      Correção de segmentação em números `26`, `27`, `38`, `39`, `43`.
