### ISSUE TITLE
Atualizar dados para estudo estatístico

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#109]
Atualizar as planilhas para estudo estatístico com os dados já finalizados da pesquisa

**Comment by SaraFadigas** [comment]
Como está a atualização dos dados @msampaio ?

**Comment by msampaio** [comment]
@SaraFadigas, as planilhas estão desatualizadas. Para atualizá-las preciso revisar o programa e implementar funções para extrair dados adicionais, como conteúdos de tempo (tarefa #99), e cruzar dados, como instrumento do compositor.

**Comment by SaraFadigas** [comment]
Certo.
