### ISSUE TITLE
Verificar técnicas estatísticas aplicáveis aos dados compositor x intervalos

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#111]
O objetivo da tarefa é verificar que técnicas estatísticas podem ser utilizadas para otimizar os dados da tabela compositor x intervalos. O objetivo principal é eliminar os ruídos gerados com os intervalos de pouca ocorrência.
Esta tabela representa o número de ocorrências dos intervalos na obra dos compositores listados. Os valores são absolutos.
Nos intervalos, m significa menor, M maior, d diminuto, P justo, dd dobrado diminuto, A aumentado
O arquivo está na pasta Dropbox/genos-choros/compositor_intervalo.xlsx

**Comment by msampaio** [comment]
Uma observação: como algumas obras têm parceria de mais de um compositor, os dados dessas obras aparecem nos números de todos os seus compositores. Dessa forma, o total de ocorrência de cada intervalo não é a soma das ocorrências daquele intervalo em todos os compositores.

**Comment by msampaio** [comment]
@SaraFadigas, eu inseri várias outras tabelas na mesma pasta Dropbox/genos-choros/. Estão em format csv. Qualquer software de planilha abre esse arquivo normalmente.

**Comment by SaraFadigas** [comment]
certo. vou olhar as tabelas

**Comment by msampaio** [comment]
Caso precise inverter colunas e linhas, veja [aqui](http://www.weliveonline.net/blog/2008/02/13/flip-rows-and-columns-in-openoffice/) como fazer.

**Comment by SaraFadigas** [comment]
Certo. Se eu tiver algum problema eu grito.. kkkk

**Comment by msampaio** [comment]
@SaraFadigas, qual o estado desta tarefa?

**Comment by SaraFadigas** [comment]
em processo.

**Comment by SaraFadigas** [comment]
@msampaio o senhor tem os dados dos intervalos encontrados nas peças de Pixiguinha? com quem foi que ele tem várias co-composições? Tem os dados dos intervalos desse outro compositor também? Preciso dessas informações para tirar as repetições.

**Comment by msampaio** [comment]
@SaraFadigas, por hora você pode ver as composições neste [arquivo json](https://github.com/msampaio/umazero/blob/refactor/json/pieces.json).
Não sei como resolver esse problema das repetições das músicas. Você tem alguma sugestão?

**Comment by SaraFadigas** [comment]
Eu tenho uma ideia, por isso pedi esse material. Eu pensei em analisar esses duos em separado. ver as porcentagens de cada um em solo e ver a participação de cada um nos duos. Não sei se vai gerar algum resultado que seja aproveitável, mas eu quero tentar, pelo menos pra eliminar todas as tentativas.

**Comment by SaraFadigas** [comment]
Esse arquivo tem a informacao sobre os intervalos? pelo que eu vi só tem a informacao de quais musica foram feitas em duo.

**Comment by SaraFadigas** [comment]
eu encontro esses dados em numeros no dropbox? caso afirmativo, qual arquivo?

**Comment by msampaio** [comment]
@SaraFadigas, não tenho como isolar esses dados neste momento, pois estou reimplementando o código para realização de consultas no programa (tarefa #110). Tão logo acabe essa implementação, irei gerar as tabelas para você.
A ideia é gerar uma tabela para cada composição que tem mais de um compositor?

**Comment by SaraFadigas** [comment]
se for melhor pra voce fazer assim, eu prefiro. nas linhas os tipos de intervalos e nas colunas as peças de um duo. uma tabela por duo, se houver mais de um.

**Comment by msampaio** [comment]
Acho que agora entendi. Você quer uma tabela de intervalos de todas as peças compostas por mais de uma pessoa. É isso?

**Comment by SaraFadigas** [comment]
Isso! mas se for mais de um duo voce separa em outras planilhas, pra ficar mais claro.

**Comment by msampaio** [comment]
Sara, apaguei as mensagens repetidas.
1. Você chama de duo a composição com mais de um compositor?
2. Você quer que eu gere uma planilha para cada peça composta por mais de um autor? São 77 obras com dois ou mais compositores (44% do total).

**Comment by SaraFadigas** [comment]
1. sim, é porque eu imagino que nao tenha composições com mais de dois compositores, mas se tiver, essa é a ideia.
2. Eu quero uma planilha pra cada parceria, com todas as peças que aquela parceria compôs, tipo, todas as peças que Pixinguinha compôs com Benedito Lacerda, por exemplo.

**Comment by msampaio** [comment]
Entendi. Em breve te passo esses dados.

**Comment by SaraFadigas** [comment]
nao precisa pressa. vou aproveitar pra fazer esse mesmo procedimento nas outras tabelas que tem no dropbox.

**Comment by msampaio** [comment]
Não gaste tempro transpondo tabelas. Prefiro que use esse tempo para modelar os dados que você precisa. Estou exatamente trabalhando na modelagem dos dados de saída do programa.

**Comment by SaraFadigas** [comment]
mas o que vai ser feito das outras tabelas? os outros dados a respeito das composicoes?

**Comment by msampaio** [comment]
Eu as gerei automaticamente. Quando concluir a implementação da saída de dados irei gerá-las novamente.

**Comment by SaraFadigas** [comment]
ah... ok
