### ISSUE TITLE
Pesquisar playback de segno e coda no MuseScore

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#14]
Verificar no manual, listas de discussão e/ou enviar pergunta aos desenvolvedores.

**Comment by EduardoNunes** [comment]
Marcos,

Aqui o vídeo que eu havia falado que  ensina a
colocar coda no Musescore.

Abraço

Eduardo

Em 5 de setembro de 2012 14:47, Marcos da Silva Sampaio <
notifications@github.com> escreveu:

> Verificar no manual, listas de discussão e/ou enviar pergunta aos
> desenvolvedores.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/msampaio/choros-contour/issues/14.

## 

Eduardo Lago

**Comment by msampaio** [comment]
Você não enviou o link. Sugiro que envie em outro email para mim. Talvez o
Github não aceite link na resposta.

Abraço,

Marcos

2012/9/15 Eduardo Lago Nunes notifications@github.com

> Marcos,
> 
> Aqui o vídeo que eu havia falado que ensina a
> colocar coda no Musescore.
> 
> Abraço
> 
> Eduardo
> 
> Em 5 de setembro de 2012 14:47, Marcos da Silva Sampaio <
> notifications@github.com> escreveu:
> 
> > Verificar no manual, listas de discussão e/ou enviar pergunta aos
> > desenvolvedores.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/msampaio/choros-contour/issues/14>.
> 
> ## 
> 
> Eduardo Lago
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/msampaio/choros-contour/issues/14#issuecomment-8584176.

## 

Marcos da Silva Sampaio

Professor de Teoria, Composição e Computação Musical
Universidade Federal da Bahia / Escola de Música

http://marcosdisilva.net
http://genosmus.com

**Comment by msampaio** [comment]
Decidimos escrever as repetições da forma por extenso.
