### ISSUE TITLE
Documentar tarefa de segmentação das melodias

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#16]
Editar a página http://genosmus.com/pesquisa/contornos/choro/guia/ e inserir um pequeno guia explicando como fazer a segmentação das melodias de choros em frases e indicando formato do arquivo.

**Comment by EduardoNunes** [comment]
Marcos,

As pausas também estarão numeradas?
Como assim indicando o formato do arquivo?

Abraço,

Em 20 de dezembro de 2012 12:11, Marcos da Silva Sampaio <
notifications@github.com> escreveu:

> do como fazer a segmentação das melodias de choros em frases e indicando
> formato do arquivo.

## 

Eduardo Lago

**Comment by msampaio** [comment]
As pausas estarão enumeradas.
O formato:
1 15
16 49
49 50

2012/12/20 Eduardo Lago Nunes notifications@github.com

> Marcos,
> 
> As pausas também estarão numeradas?
> Como assim indicando o formato do arquivo?
> 
> Abraço,
> 
> Em 20 de dezembro de 2012 12:11, Marcos da Silva Sampaio <
> notifications@github.com> escreveu:
> 
> > do como fazer a segmentação das melodias de choros em frases e indicando
> > formato do arquivo.
> 
> ## 
> 
> Eduardo Lago
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/msampaio/choros-contour/issues/16#issuecomment-11587122.

## 

Marcos da Silva Sampaio

Professor de Teoria, Composição e Computação Musical
Universidade Federal da Bahia / Escola de Música

http://marcosdisilva.net
http://genosmus.com
