### ISSUE TITLE
Marcar as frases das composições 1-10 do livro de Pixinguinha

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#18]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [guia de realização de tarefas da pesquisa](http://genosmus.com/pesquisa/contornos/choro/guia/)
- A [página da pesquisa](http://genosmus.com/pesquisa/contornos/choro/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. NÃO USAR EMAIL. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.

**Comment by msampaio** [comment]
Eduardo,

Eu preciso que você adiante a marcação das frases de pelo menos uma dessas composições o mais rápido possível. Dependo disso para criar o mockup de análise de contornos.

Abraço,

Marcos.

**Comment by msampaio** [comment]
Eduardo,

Eu coloquei os arquivos das frases dos choros 1 a 8 que você segmentou no diretório onde deve ficar "genos-choros/choros-corpus/Pixinguinha Extenso". Observe a extensão de arquivo que usei.
Preciso que você faça a segmentação das frases dos choros 9 e 10 para fechar essa tarefa.

Abraço,

Marcos

**Comment by EduardoNunes** [comment]
Marcos,

Eu vi aqui, mas vou refazer tudo me baseando pelo seu arquivo. Notei que os
meus estão todos errados. Pretendo terminar todos até quarta.

Abraço

Em 18 de fevereiro de 2013 08:59, Marcos da Silva Sampaio <
notifications@github.com> escreveu:

> Eduardo,
> 
> Eu coloquei os arquivos das frases dos choros 1 a 8 que você segmentou no
> diretório onde deve ficar "genos-choros/choros-corpus/Pixinguinha Extenso".
> Observe a extensão de arquivo que usei.
> Preciso que você faça a segmentação das frases dos choros 9 e 10 para
> fechar essa tarefa.
> 
> Abraço,
> 
> Marcos
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/msampaio/choros-contour/issues/18#issuecomment-13718718.

## 

Eduardo Lago

**Comment by msampaio** [comment]
Ok então. Lembre-se de manter a extensão .phrase e o nome do arquivo idêntico ao da partitura.

Abraço,

Marcos
