### ISSUE TITLE
Instalação de ferramentas da pesquisa

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#2]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [guia de realização de tarefas da pesquisa](http://genosmus.com/pesquisa/contornos/choro/guia/)
- A [página da pesquisa](http://genosmus.com/pesquisa/contornos/choro/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. NÃO USAR EMAIL. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.

**Comment by msampaio** [comment]
Instalar apenas os repositórios e aceitar o convite do Dropbox para a pasta da pesquisa. Deixar a instalação do Music21 para outro issue.

**Comment by EduardoNunes** [comment]
Marcos, está dando o seguinte erro na atualização:

eduardo@eduardo-desktop:~/choros-contour$ git submodule update
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
Unable to fetch in submodule path 'choros-corpus'

**Comment by msampaio** [comment]
Eduardo,

Acabei de ver que você não está na lista de permissões do submódulo choros-corpus no bitbucket. Qual o seu nome de usuário lá?

**Comment by EduardoNunes** [comment]
Meu usuário é 'Eduardo Lago Nunes'

Em 7 de agosto de 2012 15:21, Marcos da Silva Sampaio <
notifications@github.com> escreveu:

> Eduardo,
> 
> Acabei de ver que você não está na lista de permissões do submódulo
> choros-corpus no bitbucket. Qual o seu nome de usuário lá?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/msampaio/choros-contour/issues/2#issuecomment-7562119.

## 

Eduardo Lago

**Comment by msampaio** [comment]
Ok. Permissão concedida.

**Comment by msampaio** [comment]
Você precisa cadastrar sua senha pública ssh ~/.ssh/id_rsa.pub no [Bitbucket](https://bitbucket.org). Veja accounts/ssh keys
