### ISSUE TITLE
Verificar problemas de versões com arquivos da coleção Pixinguinha no Dropbox

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#21]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [guia de realização de tarefas da pesquisa](http://genosmus.com/pesquisa/contornos/choro/guia/)
- A [página da pesquisa](http://genosmus.com/pesquisa/contornos/choro/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. NÃO USAR EMAIL. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.

Verificar qual dos arquivos destes diretórios é o correto e colocar em genos-choros/choros-corpus/Pixinguinha/
#### Arquivos diferentes
- Binary files choros-corpus/choros-corpus/Pixinguinha/15 - concerto de baterias.mus and genos-choros/choros-corpus/Pixinguinha/15 - concerto de baterias.mus differ
- Binary files choros-corpus/choros-corpus/Pixinguinha/21 devagar e sempre.mus and genos-choros/choros-corpus/Pixinguinha/21 devagar e sempre.mus differ
- Binary files choros-corpus/choros-corpus/Pixinguinha/24 - domino - erro nas repeticoes.mus and genos-choros/choros-corpus/Pixinguinha/24 - domino - erro nas repeticoes.mus differ

**Comment by msampaio** [comment]
Eduardo,
Preciso que você revise estes arquivos o quanto antes. Esta é uma tarefa rápida que prefiro que você faça, pois foi você quem editou estes choros.

Marcos.

**Comment by EduardoNunes** [comment]
Marcos, 

Está tudo OK com as 3 peças, a única avaria é que a Pixinguinha 15 estava sem a anacruze, mas já coloquei e recriei outro XML.

Está havendo algum problema?

Tudo Ok com: choros-corpus/choros-corpus/Pixinguinha/15 - concerto de baterias.mus
                      choros-corpus/choros-corpus/Pixinguinha/21 devagar e sempre.mus
                      choros-corpus/choros-corpus/Pixinguinha/24 - domino - erro nas repeticoes

**Comment by msampaio** [comment]
Eduardo,

Por favor copie então estes 3 arquivos de choros-corpus/choros-corpus/Pixinguinha para genos-choros/choros-corpus/Pixinguinha. Vou remover o primeiro diretório para usarmos apenas o segundo.

Abraço,

Marcos.

**Comment by EduardoNunes** [comment]
Feito.
