### ISSUE TITLE
Editar os choros 51-60 do livro O melhor do choro vol. 2

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#23]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [guia de realização de tarefas da pesquisa](http://genosmus.com/pesquisa/contornos/choro/guia/)
- A [página da pesquisa](http://genosmus.com/pesquisa/contornos/choro/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. NÃO USAR EMAIL. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.

**Comment by kedsonj** [comment]
professor tem alguma instrução de como fazer ? é só desfazer os ritornelos e escrever por extenso msmo??

**Comment by msampaio** [comment]
nao ha instrucao especial. apenas anote as duvidas se as tiver

**Comment by kedsonj** [comment]
professor, a pasta ''o melhor do choro brasileiro vol. 2'' só tem 30 musicas...

**Comment by msampaio** [comment]
Kedson, você então pode editar essas 10 composições ao invés de expandi-las?

2013/1/23 Kedson Silva notifications@github.com

> professor, a pasta ''o melhor do choro brasileiro vol. 2'' só tem 30
> musicas...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/msampaio/choros-contour/issues/23#issuecomment-12624964.

## 

Marcos da Silva Sampaio

Professor de Teoria, Composição e Computação Musical
Universidade Federal da Bahia / Escola de Música

http://marcosdisilva.net
http://genosmus.com
