### ISSUE TITLE
Editar as repetições dos choros 41-50 do livro O melhor do choro vol. 2

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#24]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [guia de realização de tarefas da pesquisa](http://genosmus.com/pesquisa/contornos/choro/guia/)
- A [página da pesquisa](http://genosmus.com/pesquisa/contornos/choro/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. NÃO USAR EMAIL. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.

**Comment by kakauss** [comment]
Ok, Professor.

Mas estou totalmente newb aqui. :P
Ainda não consegui achar o arquivo com o livro e tal... tá tudo no dropbox?

**Comment by msampaio** [comment]
Oi, Karen.

É verdade, eu esqueci de explicar onde estão os arquivos. Você deverá
copiar cada partitura a ser trabalhada do diretório

Dropbox/genos-choros/choros-corpus/O melhor do choro brasileiro 2

para

Dropbox/genos-choros/choros-corpus/O melhor do choro brasileiro vol 2
expandido

Lembre-se de copiar a partitura antes de fazer a expansão, para não alterar
o arquivo original.
Em caso de dúvida é só perguntar. Os demais também podem responder, caso eu
demore.

Abraço,

Marcos.

**Comment by kakauss** [comment]
Olá, Professor.
Desculpa a imensa demora em responder, mas tentei fazer o que você pediu, Kedson escreveu que não tava editado (tive a mesma dúvida que ele, inclusive), esperei ele falar mais alguma coisa (algo que não aconteceu) e agora estou MUITO perdida, por isso não falei nada sobre o estado das tarefas... desculpa.

Todos os choros do livro (o melhor do choro brasileiro vol 2) estão editados?
Se não, quais faltam eu editar?
Onde estão os choros já editados e não expandidos?

Desculpa mesmo a demora em responder, mas esperei mais alguma posição sobre a minha tarefa, além da dúvida de Kedson por ti respondida e acabei me perdendo toda. :/

Abs

**Comment by msampaio** [comment]
Oi, Karen.

A coleção "O melhor do choro brasileiro 2" tem 60 peças, mas só temos 30
editadas. Eu quero que você edite as peças de número 41 a 50 (Queixas a
Sonoroso). Após editar expanda estas dez peças colocando a versão expandida
no diretório "O melhor do choro brasileiro vol 2 expandido".
Em caso de dúvida é só perguntar ;-)

Abraço,

Marcos.

**Comment by kakauss** [comment]
Ok, Professor,

mas as peças que estás a pedir não estão no diretório do dropbox com o nome do livro. Acho que foi essa a dúvida de Kedson: lá só tem os choros 1 ao 30, ou seja, as peças nº 41 a 50 não existem na pasta "o melhor do choro brasileiro vol 2".

O que faço, então?

**Comment by kakauss** [comment]
Já entendi, Professor.

Os choros pedidos estão em pdf na pasta "partituras".

:)

**Comment by msampaio** [comment]
Karen,

Como está o andamento desta tarefa? Caso tenha concluído, por favor leve em um pendrive amanhã para a aula.

Marcos.
