### ISSUE TITLE
Editar choros restantes de O Melhor do choro 2

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#28]

**Comment by AlissonGSilva** [comment]
Karen e Kedson,quais outros choros do "O melhor do choro brasileiro Vol.2 " vocês editaram e não postaram ainda no Dropbox?? Preciso dessa informação pra terminar o restante das edições e expansões pra finalizar o livro.

**Comment by msampaio** [comment]
Kedson,

Ainda não tenho os choros que Karen já editou. O choro 20 está faltando e está fora da lista de Karen. Pode começar com ele.

**Comment by kedsonj** [comment]
Prof,
Ja fiz do 31 ao 38, que estavam faltando, preciso saber se karen vai fazer
pra eu n fazer sem necessidade, ontem ela postou uns 2 que ela fez.. Vou
fazer até o 40 e o 20 e esperar okay? Se preferir que eu ja faça todos que
faltam só falar!!
Abraço

**Comment by kedsonj** [comment]
Prof,
Olhando bem, o 20 está la já, só falta os choros 39,40 e 47,48,49.
Vlw

**Comment by msampaio** [comment]
Kedson,

Faça os choros 39 e 40 e aguarde até o fim do dia para Karen dizer se fez os choros 47, 48 e 49.

**Comment by kedsonj** [comment]
Okay

**Comment by kakauss** [comment]
Marcos,

Tinha postado os choros em outra pasta sem querer, por isso você não achou.
Já os removi da pasta indevida e estão todos na pasta correta.

**Comment by msampaio** [comment]
Ótimo, Karen!
Kedson, faltam apenas os choros 39 e 40

**Comment by kedsonj** [comment]
Ja vi ,
Termino hj esses dois...
To c um problema no choro 39, n sei por quialtera de 6 rsrsrsrs
Abraço

**Comment by msampaio** [comment]
Ótimo. Caso o problema seja de edição, registre em um documento de dúvidas que tem na pasta.

**Comment by msampaio** [comment]
Faltam os choros 39 e 40 para fechar essa tarefa. Como falei, se houver problema de edição, coloque na lista de dúvidas.

**Comment by AlissonGSilva** [comment]
Kedson, o choro numero 20 é o "Expressinho" do  vol .2, no qual  está faltando.
Tem um erro de numeração na pasta, quando Dudu estava editando, ele enumerou dois numeros 5.

**Comment by msampaio** [comment]
Alisson,
É preciso ver se este número 5 é uma composição de outra coleção posta aí por engano. Kedson deverá verificar para concluir a tarefa [35](https://github.com/msampaio/choros-contour/issues/35).

**Comment by AlissonGSilva** [comment]
Marcos,
Não é engano não, estou acompanhando pelo livro.
Pra terminar o livro vol.2 faltam ; o choro numero 20 - "Expressinho" ,os choros 33 e 34 "Naquele tempo " e "Noturno" (Karen acho que você pulou esses dois choros), e o 53 o arquivo está com problemas; Kedson olhe na pasta, ele está sem formato, não consigo abrir.

Confiram o livro, na pasta choros vol.2 expandido tem as peças com a numeração correta, vou corrigir a numeração na pasta de edição do vol.2.

**Comment by msampaio** [comment]
Ótimo, Alisson.
Kedson: por favor siga as orientações de Alisson

**Comment by kedsonj** [comment]
A coleção o melhor do choro vol.2 está finalizada

**Comment by AlissonGSilva** [comment]
Finalizada as expansões do Vol.2 do melhor do choro. Só falta exportar as peças 20, 33, 34 e 53 pra XML; estou usando outro PC que ta tendo problemas com algo relacionado ao Java (não sei o por quê) , por conta disso o programa não ta conseguindo exportar.

**Comment by msampaio** [comment]
Kedson, você pode salvar estes arquivos 20, 33, 34 e 53 como xml?

**Comment by msampaio** [comment]
Kedson, por favor salve também o arquivo 19 como xml, além do 20, 33, 34 e 53. Não estou conseguindo parseá-lo.

**Comment by msampaio** [comment]
Kedson, esqueça meu pedido de salvar os arquivos como xml. Estes arquivos não são necessários na edição.
