### ISSUE TITLE
Expandir resto dos choros do Melhor do Choro 2

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#36]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [guia de realização de tarefas da pesquisa](http://genosmus.com/pesquisa/contornos/choro/guia/)
- A [página da pesquisa](http://genosmus.com/pesquisa/contornos/choro/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. NÃO USAR EMAIL. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Choros para expandir

20, 33 a 40, 44 a 53

**Comment by msampaio** [comment]
Alisson, por favor salve o xml desses arquivos e do arquivo 19. Lembre-se de salvar o xml sempre que expandir uma música. O meu programa só lê xml.

**Comment by AlissonGSilva** [comment]
O XML do 19 está lá na pasta, dos expandidos.

**Comment by msampaio** [comment]
Alisson, eu estava com problemas com o xml do choro 19. Eu descobri que posso exportar os xml com o Finale Notepad. Já exportei os choros que faltavam: 20, 33, 34 e 53. Estou fechando esta tarefa.

**Comment by AlissonGSilva** [comment]
Só uma coisa Marcos achei um erro na partitura do choro 27 "Machuca". Concertei ele agora.
Estranhei Simei dizer que a música parece incompleta, mas na verdade a música acaba no compasso 42 e não no 67.
Vou apagar o XML dela. Algum problema que deu na hora da expansão quando fiz, olhei agora e resolvi. Acho que a segmentação é a mesma, não vai mudar.

**Comment by msampaio** [comment]
Eu exportei o xml e gerei o arquivo com eventos enumerados. Há algum bug nos outros choros. Veja meu [report](https://github.com/msampaio/choros-contour/issues/51)
