### ISSUE TITLE
Mapear todos os 549 choros trabalhados

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#45]
Listar os títulos e compositores de todos os choros presentes nas coleçoes que estao sendo trabalhadas. Salvar dados em uma planilha.
As coleçoes trabalhadas estao disponíveis no projeto. Ver pasta e Dropbox.

**Comment by SimeiFerreira** [comment]
Prof. Marcos,

Terminei o mapeamento dos choros presentes em todas as coleções presentes no Dropbox, entretanto, a soma deles resultou em 347 choros, ao invés dos 549. Gostaria de saber em qual pasta do Dropbox devo colocar a planilha com o mapeamento dos choros.

Cordialmente,

Simei Ferreira.

---

 De: Marcos da Silva Sampaio notifications@github.com
Para: msampaio/choros-contour choros-contour@noreply.github.com 
Cc: SimeiFerreira soulluz@yahoo.com.br 
Enviadas: Quinta-feira, 14 de Março de 2013 12:58
Assunto: [choros-contour] Mapear todos os 549 choros trabalhados (#45)

Listar os títulos e compositores de todos os choros presentes nas coleçoes que estao sendo trabalhadas. Salvar dados em uma planilha.

**Comment by msampaio** [comment]
Bom trabalho, Simei. Estou curioso para ver o resultado. Coloque o arquivo em genos-choros/choros-corpus

**Comment by SimeiFerreira** [comment]
Obrigado Professor,

Já coloquei a planilha com o mapeamento dos choros na pasta genos-choros/choros-corpus. Se porventura eu tiver me equivocado em alguma coisa é só me avisar para que eu possa corrigir.

**Comment by msampaio** [comment]
Bom trabalho, Simei. Infelizmente eu não fui preciso quando defini a tarefa e gostaria que você a adaptasse. Veja a imagem para ter ideia de como quero a planilha. Da forma que fiz podemos classificar os dados por coleção, composição ou compositor. Observe que criei uma pasta new para você inserir os novos dados e criei uma pasta old, com os dados que você já fez.
Como o prazo desta tarefa é hoje irei adiá-la para o dia 27/03.

![Screen Shot 2013-03-20 at 06 45 54](https://f.cloud.github.com/assets/1006488/279978/27af125e-9143-11e2-96cd-58cee3a43ad0.png)

**Comment by SimeiFerreira** [comment]
Marcos,

Baixei os songbooks que estão sendo estudados na pesquisa para facilitar meu trabalho de mapeamento dos choros e também para meu acervo pessoal. O trabalho está demorando mais do que eu esperava porque encontrei uma discrepância entre os índices dos songbooks e a ordem de paginação das partituras cifradas das obras, percebi que os colegas seguiram a ordem de paginação das partituras para numerar os choros nas pastas "originais" e "expandidos". Devo seguir essa mesma ordem ou enumerar os choros no mapeamento de acordo com os índices dos songbooks?

Outra dúvida, devo colocar os nomes de quem fez as letras nos casos de obras com letras como "Carinhoso" por exemplo ou somente o nome dos compositores?

**Comment by SimeiFerreira** [comment]
Marcos,

Refiz todo o mapeamento dos choros de acordo com o modelo que você solicitou. Segui a ordem de numeração que os colegas utilizaram nas edições e inclui os nomes dos letristas no campo "compositor" dos choros que contém letra. Já inclui a planilha na pasta "choros corpus" e aguardo seu feedback.

**Comment by msampaio** [comment]
Simei, você fez uma boa escolha ao seguir a numeração já usada pelos colegas. Sobre os letristas, recomendo que os coloque em outro campo. Observe que já alterei alguns campos no arquivo, conforme figura abaixo.
![Screen Shot 2013-04-07 at 05 58 58](https://f.cloud.github.com/assets/1006488/348563/7c06cc80-9f61-11e2-9fb8-c581bd02c3ea.png)

**Comment by SimeiFerreira** [comment]
Marcos,

Já finalizei as alterações na planilha que você começou, fica faltando apenas o segundo volume do songbook do Almir Chediak para concluir o mapeamento.

**Comment by msampaio** [comment]
@SimeiFerreira , use o livro de Chediak que aparece no [Google Books](http://books.google.com.br/books?id=Lumb-LvuR8QC&printsec=frontcover&dq=songbook+choro+2&hl=en&sa=X&ei=G3U2Uer3DofA0AHr7YCICg&ved=0CC4Q6AEwAA#v=onepage&q=songbook%20choro%202&f=false) para pegar o resto das músicas. Dá para ver o índice. Veja as fotos:

![Screen Shot 2013-04-08 at 04 53 17](https://f.cloud.github.com/assets/1006488/350553/0aa502e2-a023-11e2-9980-a2c7af5a1115.png)
![Screen Shot 2013-04-08 at 04 51 49](https://f.cloud.github.com/assets/1006488/350552/06f81a44-a023-11e2-9cde-3d03a1fc5f7c.png)
