### ISSUE TITLE
Criar cadastro na Plataforma Lattes

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#59]
Criar cadastro mínimo na [Plataforma Lattes](http://lattes.cnpq.br/), com informações pessoais e graduação em andamento. Confirmar acesso ao [SIUS](http://sius.ufba.br/).

**Comment by SimeiFerreira** [comment]
Marcos,

Meu acesso ao SIUS está normal, até aproveitei para incluir alguns dados que não estavam preenchidos. Quando ao cadastro na Plataforma Lattes, não consegui concluir porque ao final do cadastro o site sempre pedia informações sobre formação concluida, upload da foto do RG ou Passaporte. Coloquei as informações do segundo grau, mas o site persistiu solicitando upload de foto obrigatória do RG ou Passaporte para concluir o cadastro. Devo escanear uma dessas fotos e fazer upload para conseguir concluir o cadastro?

Cordialmente,

Simei Ferreira.

---

 De: Marcos da Silva Sampaio notifications@github.com
Para: msampaio/choros-contour choros-contour@noreply.github.com 
Cc: SimeiFerreira soulluz@yahoo.com.br 
Enviadas: Quarta-feira, 3 de Abril de 2013 17:22
Assunto: [choros-contour] Criar cadastro na Plataforma Lattes (#59)

Criar cadastro mínimo na Plataforma Lattes, com informações pessoais e graduação em andamento. Confirmar acesso ao SIUS.

**Comment by msampaio** [comment]
@SimeiFerreira , se a Plataforma Lattes pede a imagem do seu RG, você deve enviar.

**Comment by SimeiFerreira** [comment]
Tudo bem então, vou escanear e enviar.

**Comment by msampaio** [comment]
@SimeiFerreira , avise aqui quando o seu cadastro Lattes tiver sido ativado pelo CNPQ.

**Comment by SimeiFerreira** [comment]
Certo.

---

 De: Marcos da Silva Sampaio notifications@github.com
Para: msampaio/choros-contour choros-contour@noreply.github.com 
Cc: SimeiFerreira soulluz@yahoo.com.br 
Enviadas: Quinta-feira, 11 de Abril de 2013 12:24
Assunto: Re: [choros-contour] Criar cadastro na Plataforma Lattes (#59)

@SimeiFerreira , avise aqui quando o seu cadastro Lattes tiver sido ativado pelo CNPQ.

**Comment by SimeiFerreira** [comment]
Marcos,

Meu cadastro Lattes já está publicado. Segue link para acesso logo abaixo:

http://lattes.cnpq.br/4348635947958623

Abraços,

Simei Ferreira.

---

 De: Marcos da Silva Sampaio notifications@github.com
Para: msampaio/choros-contour choros-contour@noreply.github.com 
Cc: SimeiFerreira soulluz@yahoo.com.br 
Enviadas: Quinta-feira, 11 de Abril de 2013 12:24
Assunto: Re: [choros-contour] Criar cadastro na Plataforma Lattes (#59)

@SimeiFerreira , avise aqui quando o seu cadastro Lattes tiver sido ativado pelo CNPQ.

**Comment by msampaio** [comment]
Ótimo! Fechando tarefa...
