### ISSUE TITLE
Verificar problemas com arquivo 27, da coleção O melhor do choro vol. 2

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#60]
O programa de análise de contornos está quebrando ao processar o arquivo 27 - machuca. O problema pode estar no arquivo '.phrase' ou '.xml'. Verificar se há algum erro aparente nestes arquivos e informar comentando a tarefa no github.

O erro segue abaixo para registro.

```
Traceback (most recent call last):
  File "data.py", line 21, in <module>
    melhorChoro_2 = phrase.make_phrase_collection("O Melhor do Choro volume 2", False)
  File "/Users/marcos/Dropbox/ongoing/choros-contour/phrase.py", line 125, in make_phrase_collection
    return [make_phrase(f, music21_obj) for f in files]
  File "/Users/marcos/Dropbox/ongoing/choros-contour/phrase.py", line 106, in make_phrase
    contour = Contour(phr)
  File "/Users/marcos/.virtualenvs/choros/lib/python2.7/site-packages/music21/contour/contour.py", line 134, in __init__
    self.items = self.remove_adjacent(midi_args_translation)
  File "/Users/marcos/.virtualenvs/choros/lib/python2.7/site-packages/music21/contour/contour.py", line 176, in remove_adjacent
    return [a for a, b in groups if a != b] + [list[-1]]
IndexError: list index out of range
```

**Comment by msampaio** [comment]
@SimeiFerreira , este erro "list index out of range" significa que o número de eventos na música é menor do que os indicados nas frases. Conferi e percebi que a música tem 213 eventos e as frases vão até o evento 348. A tarefa para corrigir o problema é refazer a segmentação.

**Comment by SimeiFerreira** [comment]
Certo Marcos,
Estou colocando as tarefas em dia, minha intenção é estar com tudo pronto já nesse fim de semana.

**Comment by SimeiFerreira** [comment]
Marcos,
Refiz a segmentação do Choro "Machuca", de fato eu devo ter me confundido no momento em que fiz a primeira segmentação da referida obra, peço desculpas pela minha falha.
Veja se agora funciona no programa.

**Comment by msampaio** [comment]
Funcionando.
