### ISSUE TITLE
Verificar expansão de 27 - Flor Amorosa (O melhor do choro brasileiro vol 1)

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#64]
Verificar na partitura original se a expansão dessa música foi feita corretamente. Há uma frase entre os eventos 358 e 382 e outra iniciando em 387. Confirmar as notas dos eventos 383 a 386. (Vide imagem)

![Screen Shot 2013-04-18 at 15 22 25](https://f.cloud.github.com/assets/1006488/398279/45857fba-a855-11e2-9c6f-0be8bede62d3.png)

**Comment by AlissonGSilva** [comment]
Marcos esse choro ele tem um ritornello confuso, escrevi no arquivo de texto "Anotações,dúvidas e problemas" na pasta das expansões do Vol.1 . No original ele indica um rittornelo depois do evento 285, mas não diz de onde devo retornar.

**Comment by AlissonGSilva** [comment]
"Flor amorosa" Ritornello confuso no quarto sistema. Ritornello confuso no ultimo sistema da partitura original.

**Comment by msampaio** [comment]
@AlissonGSilva, pela audição eu percebi que há dois possíveis erros:
1. O ritornello não existe
2. O ritornello último compasso do ritornello seria uma casa 2 para a volta para o início da música. O fragmento indicado por 2, abaixo, é a anacruse do tema principal. No entanto não há uma casa 1. Esta casa 1 deveria voltar para o local indicado pelo número 1, abaixo.
![screen shot 2013-04-30 at 10 27 31](https://f.cloud.github.com/assets/1006488/444102/3dfdf36e-b19a-11e2-9f0e-b2f02e37832d.png)
Recomendo então que você refaça a expansão considerando que o ritornello não existe. Não vamos compor a casa 1 que falta ;-)

**Comment by AlissonGSilva** [comment]
Ok!

**Comment by AlissonGSilva** [comment]
Refeita a expansão do choro 27 - Flor Amorosa.
Não estou conseguindo exportar nenhum arquivo em XML,avisa que é um
problema no meu JAVA, já instalei e reinstalei e nada resolve. Acho que só
formatando a maquina, to usando o PC pessoal de casa pra trabalhar que ta
dando uns problemas, por estar sobrecarregado (ele precisa de uma
formatação).

**Comment by msampaio** [comment]
Bom trabalho, @AlissonGSilva. Estou fechando esse ticket. Já atualizei o arquivo `27 - flor amorosa - numbered.xml`. Quanto ao xml, se não está conseguindo agora, deixe para depois. Adiante as expansões.
Abraço,
Marcos
