### ISSUE TITLE
Corrigir arquivos xml das músicas 41 e 44 de O melhor do choro brasileiro vol 2

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#65]
O choro 41 (e possivelmente o 44) está com problemas. Seu arquivo .form tem mais eventos do que o seu arquivo .xml. Eu observei que você editou o arquivo 'numbered' e ele ficou maior. Se fez a edição para corrigi-lo, peço que faça apenas em 41 - queixas.xml, e não em 41 - queixas numbered.xml. Este segundo arquivo é descartável.

![Screen Shot 2013-04-26 at 18 55 36](https://f.cloud.github.com/assets/1006488/433109/6b5e21a2-aebc-11e2-8975-7b904165bbad.png)

**Comment by SimeiFerreira** [comment]
Marcos,

Eu editei os xml enumerados manualmente porque os erros de expansão ainda estavam presentes nos mesmos. Não sabia que os mesmos eram descartáveis. Corrigirei os xml não enumerados, mas sem a numeração fica mais complicado e demorado comparar o número de eventos do arquivo .form com o arquivo .xml.

**Comment by SimeiFerreira** [comment]
Arquivos xml dos choros 41, 44 e 50 corrigidos. Gerei novos xml a partir dos arquivos mus cuja expansão eu havia corrigido anteriormente e substitui os que estavam na pasta pelos novos. Veja se o problema persiste.

**Comment by msampaio** [comment]
@SimeiFerreira, a ideia é sempre facilitar. Sempre que precisar fazer uma correção no xml faça no 'arquivo.xml', não no 'arquivo numbered.xml'. Após a correção é só me falar que eu gero um novo 'numbered'.
Vou verificar se o problema persiste e te aviso.

**Comment by SimeiFerreira** [comment]
Foi mal Marcos, fico no aguardo.

**Comment by msampaio** [comment]
@SimeiFerreira, ainda está quebrando aqui. Faça o seguinte.
1. Corrija a expansão pelo arquivo 41 - queixa.xml
2. Avise quando a correção estiver pronta
3. Aguarde eu gerar o arquivo enumerado
4. A partir do arquivo enumerado (feito com a partir da sua correção), refaça o arquivo de segmentação 41 - queixa.form
5. Avise quando o arquivo de segmentação estiver pronto

**Comment by SimeiFerreira** [comment]
Marcos,

O arquivo "41 - queixas.xml" que está no dropbox é justamente o que eu gerei a partir da correção do arquivo MUS do choro 41 - Queixas. O arquivo xml do referido choro que continha o erro foi substituido no momento em que passei o novo xml já corrigido.

Você prefere passar para o passo 3 da tarefa ou gerar no seu software um novo arquivo xml não enumerado a partir do arquivo .mus que eu corrigi, considerando que o que eu gerei está quebrando?

**Comment by msampaio** [comment]
Simei.

Estou fora da cidade e sem computador. Na segunda feira vemos isso.

**Comment by SimeiFerreira** [comment]
Tranquilo Marcos, vou adiantando as segmentações até lá.

**Comment by msampaio** [comment]
@SimeiFerreira, eu gerei um arquivo enumerado com base no seu '41 - queixas.xml'. Este arquivo tem 484 eventos. Você pode conferir se ele está certo e atualizar o arquivo de segmentação de forma? Se houver mais algum problema me avise.

**Comment by SimeiFerreira** [comment]
Pronto Marcos, agora tá tudo certinho. Já corrigi o arquivo .form e o coloquei no dropbox.

**Comment by SimeiFerreira** [comment]
A propósito, você poderia gerar novos arquivos xml enumerados dos choros 44 e 50? Assim como no 41 eu corrigi os erros de expansão nos respectivos arquivos mus e gerei novos arquivos xml não enumerados já corrigidos. É bom que você vê também se algum deles está quebrando aí pra você.

**Comment by msampaio** [comment]
Bom trabalho. Já gerei os xml enumerados dos choros 44 e 50. Estão no Dropbox.

**Comment by SimeiFerreira** [comment]
Marcos, você gerou os xml enumerados dos choros 44 e 50 a partir dos arquivos xml corrigidos que eu gerei? Pergunto porque nos arquivos xml enumerdos persistem os erros que eu havia corrigido no arquivo mus e que continuam corrigidos nos arquivos xml não enumerados.

**Comment by msampaio** [comment]
@SimeiFerreira, eu já tinha gerado. Por via das dúvidas gerei um novo xml a partir do seu mus e criei um numbered.xml a partir desse novo xml. Veja se está certo.

**Comment by SimeiFerreira** [comment]
Agora está tudo ok Marcos.

**Comment by msampaio** [comment]
Ótimo. Os arquivos .form dos choros 41 e 44 também estão corretos?

**Comment by SimeiFerreira** [comment]
Desculpe pela demora em responder Marcos, o número de eventos agora está equivalente nos arquivos numbered xml e .form.

**Comment by msampaio** [comment]
Ótimo. Fechando issue.
