### ISSUE TITLE
Melhorar tabela com dados musicológicos das coleções

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#73]
### Instruções

A tabela está na pasta do Dropbox da pesquisa, em `genos-choros/choros-corpus/informacao-corpus-choros.xls`.
O trabalho consiste em usar uma forma única para o nome de cada compositor. Por exemplo, usar `Angelo Reale` ao invés de `A. Reale`, `A Reale` e outras possibilidades. O [Dicionário Cravo Albim](http://www.dicionariompb.com.br/) pode servir de referência para obter os nomes corretos dos compositores.
Separar o nome de cada compositor ou autor de letra em colunas diferentes. Por exemplo, esta entrada:

Música            | Compositor
Naquele tempo | Pixinguinha e Benedito Lacerda

Deve ser feita dessa forma

Música            | Compositor 1 | Compositor 2
Naquele tempo | Pixinguinha   | Benedito Lacerda
### Observações:
1. O trabalho deve ser feito diretamente no arquivo na pasta do Dropbox. Não editar a planilha fora do Dropbox para depois salvar de volta na pasta.
2. Em caso de dúvida, inserir a pergunta como comentário da tarefa. Com isso é possível organizar todas as questões em torno de cada tarefa.

**Comment by ZeRodriguez** [comment]
Professor, só pra esclarecer:

Coluna A - Coleção
Coluna B - Número
Coluna C - Título
Coluna D - Compositor
Coluna E - Letra

Eu irei mexer apenas nas colunas D e E. É para fazer desde início, não é isso? Pois na reunião você havia dito que seria apenas o da coleção "Songbook Almir Chediak".
Outra dúvida é em relação aos autores. Se por um acaso eu não souber quem compôs e quem escreveu a letra?
Como é que eu faço?

**Comment by ZeRodriguez** [comment]
Tô fazendo desde o início fessô.
Só outra dúvida. Alguns casos têm três nomes, por exemplo:

Ingênuo | Pixiguinha | Benedito Lacerda | Paulo César Pinheiro

Como faço? Há problema se Paulo vier antes de Benedito e vice-versa?
Perdoe-me as dúvidas idiotas. Tô aprendendo!!! Hehehe

**Comment by ZeRodriguez** [comment]
Já está tudo feito fessô. Pode dá uma olhada lá antes de ler as minhas dúvidas.
Fico no aguardo. Bom resto de domingo e até terça! =D

**Comment by msampaio** [comment]
Olá, @ZeRodriguez. Excelente trabalho! Eu preciso apenas que você coloque os nomes abreviados por extenso. Por exemplo, M d'Agostino. Você pode pesquisar por esses nomes no [Dicionário Cravo Albim](http://www.dicionariompb.com.br/). Pesquise pelo sobrenome ou títulos das músicas.

**Comment by ZeRodriguez** [comment]
Beleza fessô!
Eu tive esse pensamento, justamente nesse autor, M. d'Agostino. Procurei na internet e não achei. Agora com esse dicionário facilita. Sobre outro autor, Francisco Soares, fiquei receoso sem saber se era o mesmo, mas o renomeei para Canhoto da Paraíba, que foi o que apareceu primeiro.

**Comment by ZeRodriguez** [comment]
Milton d'Agostino, Carolina Cardoso de Menezes e João Silva foram os únicos fessô.
Aníbal Augusto Sardinha eu não sabia que era Garoto. Como aparecia uma única vez com o nome completo, renomeei para o apelido. Dá uma olhada lá. Qualquer coisa, tamos aí!

**Comment by msampaio** [comment]
Ótimo trabalho! Estou fechando a tarefa, considerando concluída.

**Comment by msampaio** [comment]
@ZeRodriguez, eu precisei reabrir essa tarefa. Observei que há nomes idênticos com diferença de acentuação (Cristóvão e Cristovão), e nomes parecidos que não sei se são pessoas diferentes (Canhoto, Canhotinho e Canhoto da Paraíba).
Preciso que você verifique esse nomes para saber se são realmente pessoas diferentes e corrija as duplicidades com acentuação.
Use a [tabela de compositores](http://umazero.genosmus.com/collections.html) que fiz com base em seu arquivo.

**Comment by ZeRodriguez** [comment]
Professor, eu prestei atenção nessa questão da pontuação. Então passou desapercebido, corrigirei. Me perdoe.
Quando aos nomes, verifiquei sim. Canhoto é referente à Américo Jacomino quando Canhoto da Paraíba refere-se à Chico Soares. Vou retificar a questão das acentuações. Abraço

**Comment by ZeRodriguez** [comment]
Professor, tarefa concluída. Além de Cristóvão, o erro ocorreu com Luíz Santos, o único dos "Luiz" que recebe acento. Já o Luiz Americano, em apenas um lugar eu encontrei o Luiz com "s" (Luis). Mesmo na tabela de compositores, de 13 vezes, apenas 1 aparece com "s", então mantive com "z". Tarefa concluída. Qualquer falha, é só informar. Abraço
