### ISSUE TITLE
Coletar informações musicológicas sobre compositores

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#85]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [guia de realização de tarefas da pesquisa](http://genosmus.com/pesquisa/contornos/choro/guia/)
- A [página da pesquisa](http://genosmus.com/pesquisa/contornos/choro/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. NÃO USAR EMAIL. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.
### Instruções específicas

Levantar informações sobre cada compositor: ano de nascimento, ano de morte e instrumento principal. Ver exemplo na figura abaixo.
Quando se tratar de letrista, inserir `-` no lugar do instrumento.
O arquivo está na pasta Dropbox da pesquisa, em `genos-choros/choros-corpus/informacao-corpus-choros.xls`.
Procurar [Dicionário Cravo Albim](http://www.dicionariompb.com.br/)

![screen shot 2013-06-12 at 19 25 34](https://f.cloud.github.com/assets/1006488/645881/31bea0c8-d3b2-11e2-9488-82f6e003302a.png)

**Comment by daniloabrahao** [comment]
Dos compositores de 1 a 141 que estão em branco são aqueles que não encontrei informação mesmo aqui na internet. De 142 em diante os que estão em branco não constavam no Dicionário Cravo Albin, no site Samba choro e outras "enciclopédias" da mpb. Continuarei a pesquisa sobre estes últimos. Mas não sei o que fazer sobre estes outros.

**Comment by msampaio** [comment]
@daniloabrahao, você pode colocar o arquivo que você fez no Dropbox? Assim não há risco de conflito de versões.

**Comment by daniloabrahao** [comment]
Marcos,

O tentei colocar na pasta do dropbox, mas apareceu a seguinte mensagem:
"Não foi possível sincronizar (não há espaço disponível)"
Sei que o dropbox tem um limite de espaço. Eu nunca compartilhei nada, mas
tem muitas coisas que que outras pessoas compartilharam comigo. Estou
fazendo da maneira errada?

**Comment by msampaio** [comment]
@daniloabrahao, recomendo que você limpe alguma coisa no seu Dropbox, pois usaremos sempre ele para a pesquisa. Você pode ver quais as pastas que ocupam mais espaço e removê-las do seu Dropbox. Eu sempre recomendo usar o Dropbox apenas para o que é essencial. Por exemplo, eu posso conseguir novamente uma gravação ou partitura de um compositor como Bach ou Beethoven, mas não posso com as minhas próprias músicas. Da mesma forma não posso conseguir novamente o material de pesquisa que nós estamos desenvolvendo. Então sugiro revisar o que está enchendo sua caixa com o foco no que é essencial ficar.

**Comment by msampaio** [comment]
@daniloabrahao, eu olhei o arquivo que você mandou por email para poder adiantar o trabalho. Bom trabalho, você está no caminho certo. Veja se você encontra as informações que faltam sobre compositores neste livro na biblioteca da EMUS:

CAZES, Henrique. . Suite gargalhadas : cento e tantas historias engracadas sobre musica e musicos. Rio de Janeiro: Jose Olympio, 2002. 203 p. ISBN 8503007436
Número de Chamada: 780.92 C386

Por favor fique atento para ter um padrão de 'espaço vazio' na planilha. Em alguns lugares há `-` e em outros `.`. Veja a figura abaixo.

![screen shot 2013-07-03 at 08 53 50](https://f.cloud.github.com/assets/1006488/742863/2744f56c-e3d8-11e2-9d32-63cf39d77fdc.png)

Eu verifiquei que alguns compositores aparecem com grafia do nome errada. Por exemplo, Radamés Gnattali
e Radamés Gnattalli. Pode manter apenas os que têm grafia correta.

**Comment by daniloabrahao** [comment]
Ok Marcos,

Obrigado pela atenção, mesmo!
Eu consegui resolver a questão do Dropbox e, enfim, está lá... Vou
continuar o trabalho!
Desculpe os erros e todo este problema que arrumei com o Dropbox!

Abs!
Danilo

**Comment by msampaio** [comment]
Sem problema. Em caso de dúvida é só perguntar.

**Comment by daniloabrahao** [comment]
Exitem dois compositores apelidados como "Ratinho", um Português e letrista de samba e o outro brasileiro que integrou o duo "Jararaca e Ratinho" e que se chama Severino Rangel Carvalho. "Ratinho" e "Severino Rangel Carvalho" estão na lista.  Não sei com os dados de quem preencherei o item "Ratinho".

Esta lista que estou preenchendo é formada por nomes que foram tirados dos Songbooks? Posso sanar esta dúvida sabendo o nome de uma letra que o referido como Ratinho, na lista, compôs. Acho que acessando os songbooks eu posso resolver mais problemas.

**Comment by msampaio** [comment]
@daniloabrahao, todos os nomes de compositores foram extraídos dos songbook. Vale a pena você usar os nomes das músicas para confirmar de quem se trata. Talvez ajude a resolver esse problema com Ratinho/Severino Rangel Carvalho.

**Comment by daniloabrahao** [comment]
@msampaio, agora estou pesquisando em enciclopédias que estão na biblioteca da EMUS. Todavia, existem alguns muitos compositores os quais não encontrei informação nenhuma. E receio não encontrar até o prazo final. Você sabe de algum site do governo que tenha o registro das pessoas? Seria bem útil no caso dos compositores que não utilizavam apelidos e aqueles que descobri o nome completo.

**Comment by msampaio** [comment]
@daniloabrahao, bom trabalho. Eu não sei de um site que possamos ver informações a partir do nome das pessoas. Falarei com alguns colegas da área de Etnomusicologia para saber como podemos proceder. Ao final da tarefa eu quero que você relate aqui quais os problemas encontrados e como você procedeu para soluciona-los.

**Comment by daniloabrahao** [comment]
Ok!

**Comment by msampaio** [comment]
@daniloabrahao, um colega me recomendou procurar informações sobre os compositores na [Enciclopédia da Música Brasileira: Samba e Choro](http://publifolha.folha.com.br/catalogo/livros/135477/). Você pode olhar e informar aqui?

**Comment by msampaio** [comment]
@daniloabrahao, suspenda temporariamente a pesquisa relacionada aos compositores que não estão listados em http://umazero.genosmus.com/collections.html#composers. Nesse momento o mais importante para nós será focar na coleção 'O melhor do choro'. Eu removi os compositores da coleção de Almir Chediak.

**Comment by daniloabrahao** [comment]
@msampaio, eu já utilizei esta Enciclopédia semana passada na EMUS.
Ok, vou redirecionar minha atenção para os que faltam desta lista.

**Comment by msampaio** [comment]
@daniloabrahao, conforme falei na [reunião de ontem](http://genosmus.com/2013/07/ata-da-reuniao-de-23072013/), insira aqui as referências que você consultou durante a tarefa. Vale a pena cadastra-las no [Mendeley](http://www.mendeley.com/). Se você não souber fazer isso eu te ensino.

**Comment by daniloabrahao** [comment]
Ok,
As fontes da web também?

**Comment by msampaio** [comment]
Sim.

**Comment by daniloabrahao** [comment]
@msampaio, desculpe a demora em responder.
Não sei cadastrar a bibliografia no Mendeley, ainda. Vou tentar aprender aqui, de qualquer forma vou deixar as fontes bibliográficas da minha tarefa num próximo comentário aqui.

**Comment by daniloabrahao** [comment]
Referências Bibliográficas:
1. MARCONDES, Marco Antônio; Enciclopédia da música brasileira: erudita, folclórica e popular. 2 ed. São Paulo: Art Editora, 1998.
2. Dicionário Cravo Albin da Música Popular Brasileira: http://www.dicionariompb.com.br/
3. A Agenda do Samba & Choro: http://www.samba-choro.com.br/artistas
4. MPB CIFRANTIGA: http://cifrantiga.blogspot.com.br/
5. Ao Chiado Brasileiro: http://aochiadobrasileiro.webs.com/principal.htm
6. MPB DA ANTIGA: http://mpbantiga.blogspot.com.br/
7. Bossa Brasileira: http://bossa-brasileira.blogspot.com.br/
8. Música Chiado/Gravações Raras: http://musicachiado.webs.com/GravacoesRaras/GravacoesRaras.htm
9. Wikipédia, a enciclopédia livre: http://www.wikipedia.org/

**Comment by msampaio** [comment]
Sem problema, @daniloabrahao. Você usou alguma referência além dessas quatro?

**Comment by daniloabrahao** [comment]
Sim, @msampaio. 
Algumas das outras são referência sem muita credibilidade, como blogs pessoais... Devo colocar mesmo assim?

**Comment by msampaio** [comment]
Coloque sim ;-)

**Comment by daniloabrahao** [comment]
OBS: O nome do compositor "Paulo Helio Delmiro", presente na lista, está errado. "Hélio Delmiro" é o nome correto e "Marceneiro Paulo" nome de sua composição.

**Comment by msampaio** [comment]
Qual a coleçāo?

**Comment by daniloabrahao** [comment]
Songbook CHORO vol.3 Almir Chediak.

**Comment by msampaio** [comment]
@daniloabrahao, por favor corrija o nome dele e de composição nas planilhas `Mapeamento_dos_choros.xls` e `informacao-corpus-choros.xls`.

**Comment by daniloabrahao** [comment]
@msampaio, será que você pode me explicar como cadastrar as referências bibliográficas no Mendeley? Se preferir, eu posso levar meu computador amanhã na reunião.

**Comment by msampaio** [comment]
@daniloabrahao, você já consegue cadastrar as referências no Mendeley?

**Comment by daniloabrahao** [comment]
Não consegui, @msampaio. Baixei o Mendeley, mas ainda não sei como cadastrar...Vi umas coisas de Refworks, mas tinha que fazer upload de arquivo. Eu realmente não entendi.

**Comment by msampaio** [comment]
@daniloabrahao, em breve farei um screencast ou um post explicando como cadastrar as coisas no Mendeley. Durante a redação do artigo de choros nós faremos esse cadastro.

**Comment by daniloabrahao** [comment]
Ok!
