### ISSUE TITLE
Verificar aplicabilidade da Teoria dos Erros nos dados levantados

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#93]
Verificar se é há melhoria significativa no entendimento dos dados com a aplicação de desvio padrão, acuracidade, precisão, nível de confiança e outros conceitos relacionados a medidas.

**Comment by msampaio** [comment]
@SaraFadigas, atribuí essa tarefa pra você.

**Comment by SaraFadigas** [comment]
Certo. Qual o prazo para conclusão dessa tarefa?

**Comment by SaraFadigas** [comment]
Onde encontro na pasta os dados da pesquisa?

**Comment by msampaio** [comment]
@SaraFadigas, a princípio o prazo é dia 16. Nāo defini com precisāo por nāo saber exatamente quanto tempo será necessário para concluir a tarefa.
Veja os dados no site umazero.genosmus.com. Irei te enviar as tabelas com os valores.

**Comment by SaraFadigas** [comment]
essa comparacao será feita com dados antigos e esse atuais, ou eu farei a comparacao desses com os novos que o pessoal vai atualizar?

**Comment by SaraFadigas** [comment]
Eu vou precisar dos dados numéricos referentes aos graficos do "Pitch". Em quais arquivos posso achar esses dados?

**Comment by msampaio** [comment]
@SaraFadigas, dentro da pasta `genos-choros` eu criei a subpasta `estatistica` com o arquivo `dados-intervalos.xls`. Esta tabela é apenas provisória, para você ver o que pode adiantar. Nela há o percentual de cada tipo de intervalo entre os compositores com maior número de obras. Nos próximos dias irei te dar dados melhores para trabalhar.

**Comment by msampaio** [comment]
@SaraFadigas, eu criei arquivos em formato '.csv' com os dados levantados na mesma subpasta `estatistica`. Basta abrir em um software de planilha e processar. Nestes arquivos os valores são absolutos. Se tiver dúvidas é só perguntar por aqui.

**Comment by msampaio** [comment]
@SaraFadigas, qual o estado desta tarefa?

**Comment by SaraFadigas** [comment]
Nao concluido.

**Comment by SaraFadigas** [comment]
Em processamento de informacoes pra ser mais exata. Tenho algum prazo para entrega? Posso adiantar um resultado parcial.

**Comment by msampaio** [comment]
@SaraFadigas, aguarde apenas a conclusão da tarefa #109. Iremos focar no artigo resultante da pesquisa com choros apenas daqui a uma semana.
