### ISSUE TITLE
Criar funções para gerar dados para análise estatística

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#94]
Estas funções deverão resultar em tabelas para a realização de estudo estatístico. Esta tarefa possibilitará o levantamento de dados mais significativos para a realização da tarefa #93.

**Comment by msampaio** [comment]
É necessário criar uma função que processe também os dados usados em gráficos de dispersão.
É interessante implementar a geração automática de arquivos `.xls` para agilizar o processo. O pacote [Python-Excel](http://www.python-excel.org/) tem esse recurso.

**Comment by SaraFadigas** [comment]
Estou trabalhando nisso.

**Comment by msampaio** [comment]
Oi, @SaraFadigas. Na verdade essa tarefa #94 é minha e se refere a funções do programa para te dar os dados que você precisa para trabalhar. A sua tarefa é a #93 ;-)

**Comment by SaraFadigas** [comment]
O senhor tem disponibilidade para se reunir comigo, pra eu tirar eventuais dúvidas, amanhã? Tenho disponível das 11h as 15h.
