### ISSUE TITLE
Revisar segmentações dos choros 11 e 16 da coleção de Pixinguinha

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#95]
Estes choros têm períodos segmentados com uma única frase. Corrigir.

**Comment by ZeRodriguez** [comment]
@msampaio, a número 11 ficou bem diferente. Já a número 16, acrescentei só um link e mudei uma marcação de frase. Agora, como faço? Excluo o que já está no dropbox e coloco o meu no lugar?

**Comment by msampaio** [comment]
@ZeRodriguez, para essas tarefas você pode editar os arquivos direto no Dropbox. É a melhor solução. O Dropbox guarda as versões antigas e sempre podemos voltar a elas se necessário.

**Comment by ZeRodriguez** [comment]
Feito!
