### ISSUE TITLE
Expandir as repetições dos choros 60-72 do livro O melhor de Pixinguinha

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#97]
### Instruções gerais
- Verificar o prazo de entrega da tarefa (milestone)
- Verificar [guia de realização de tarefas da pesquisa](http://genosmus.com/pesquisa/contornos/choro/guia/)
- A [página da pesquisa](http://genosmus.com/pesquisa/contornos/choro/) contém outras informações adicionais
- Toda a discussão acerca desta tarefa deverá ser feita usando os comentários da tarefa. NÃO USAR EMAIL. O GitHub organiza a discussão e deixa registrada. É fácil encontrar depois.

**Comment by AlissonGSilva** [comment]
Marcos já expandi, está faltando o choro 72 na pasta dos originais, e os arquivos enumerados para segmentação.

**Comment by msampaio** [comment]
@AlissonGSilva, eu estou sem o livro original em mãos. Pedirei que um colega escaneie esse choro 72 e colocarei na pasta do Dropox. Enquanto isso aproveite para adiantar outras tarefas.

**Comment by msampaio** [comment]
@AlissonGSilva, coloquei a coleção "O Melhor de Pixinguinha" em PDF na pasta `partituras`, no Dropbox. Você pode editar, expandir e então me avisar para eu gerar os arquivos enumerados.

**Comment by AlissonGSilva** [comment]
Marcos esse livro só tem 71 choros, já expandi eles todos, falta só você gerar os arquivos enumerados pra finalizar.

**Comment by msampaio** [comment]
@AlissonGSilva,
1. Os arquivos enumerados já estão na pasta do Dropbox.
2. Observe que há arquivos salvos como `nome .form`, ao invés de `nome.form`. Aproveite e corrija-os.
3. As músicas 67 e 68 têm mesmo nome de arquivo.

**Comment by AlissonGSilva** [comment]
Os choros 67 e 68; os nomes são "Rosas" mesmo, só que o 68 é "Rosa" (Evocação) e o 67 é só "Rosa".

**Comment by msampaio** [comment]
@AlissonGSilva, corrija o `.form` desta música:

```
Error in file choros-corpus/O Melhor de Pixinguinha/70 - oculto.form
12: Error in p/l lines
15: p 713 829
```

**Comment by AlissonGSilva** [comment]
Ok Marcos, já corrigi o erro que tinha.
